### ISSUE TITLE
Unnecessesary observed data sets?

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/Erythromycin-Midazolam-DDI#3]
6 observed data sets claim to contain AUC ratio, but the unit in the observed data column is [µmol/l]
None of those datasets is used in any simulation, so I guess they can be safely removed?
![grafik](https://user-images.githubusercontent.com/25061876/159341387-7fc80827-31fb-4665-b7fe-4278c4d74f59.png)
![grafik](https://user-images.githubusercontent.com/25061876/159341508-cea447a0-707d-4862-bb5b-2b747907e0d6.png)

This dataset has the same unit inconsistensy, but is used by 1 simulation:
![grafik](https://user-images.githubusercontent.com/25061876/159341776-7a631e6c-0e13-4cfb-ade4-c6b0bbf59f35.png)
![grafik](https://user-images.githubusercontent.com/25061876/159341939-f8c53c4e-bcd4-442e-9b80-974fa4aa4c65.png)

**Comment by sfrechen** [comment]
These data were used to inform model buidling (see evaluation report).

**Comment by Yuri05** [comment]
well, then the data is at least malformed. Either the unit is wrong, or it's not the AUC Ratio but... just AUC?

**Comment by sfrechen** [comment]
> well, then the data is at least malformed. Either the unit is wrong, or it's not the AUC Ratio but... just AUC?

@AndreDlm

**Comment by AndreDlm** [comment]
Well, as described in the evaluation report [here](https://github.com/Open-Systems-Pharmacology/OSP-PBPK-Model-Library/blob/master/Erythromycin/Erythromycin_evaluation_report.md#234-autoinhibition), it's the theoretical AUC of midazolam given the observed AUCR. In the simulation we created a dummy reaction to be able to simulate the AUC as if it was a model output like concentration (i.e. not as a posterior estimate after obtaining the simulation results). This is why it has the unit of a concentration, otherwise PK-Sim would not accept it in the PI. I guess that could in principle be changed in MoBi, but then the error would pop up there.
